from .Elemento import *
from .integradorRectangular import *
from .integradorTriangular import *
from .SerendipityC import *
from .CuadrilateroL import *
from .TriangularC import *
from .TriangularL import *
from .FEM import *
from .NoLocal import *